train:
  _target_: torch.utils.data.ConcatDataset # we can concat datasets if we want to
  datasets:
    - _target_: src.datasets.LibrispeechDatasetKaggle
      part: "train-clean-100"
      max_audio_length: 20.0
      max_text_length: 200
      instance_transforms: ${transforms.instance_transforms.train}
    - _target_: src.datasets.LibrispeechDatasetKaggle
      part: "train-clean-360"
      max_audio_length: 20.0
      max_text_length: 200
      instance_transforms: ${transforms.instance_transforms.train}
    - _target_: src.datasets.LibrispeechDatasetKaggle
      part: "train-other-500"
      max_audio_length: 20.0
      max_text_length: 200
      instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.LibrispeechDatasetKaggle
  part: "dev-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
